import { ConversationPreview } from '../models/conversation.model';
import { Message } from '../models/message.model';

export const MOCK_CONVERSATIONS: ConversationPreview[] = [
  {
    id: 'conv-1',
    participant: {
      id: 'user-2',
      name: 'Dr. Sara Al-Mansouri',
      avatarUrl: null,
      role: 'specialist',
      isOnline: true,
      lastSeenAt: null,
      bio: 'Certified Life & Career Coach with 10+ years of experience helping professionals achieve clarity and direction.',
      rating: 4.9,
      reviewCount: 134,
      specialization: 'Career Coaching & Life Development',
    },
    lastMessage: 'Your next session is confirmed for Thursday at 3 PM.',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    participant: {
      id: 'user-3',
      name: 'Ahmed Khalil',
      avatarUrl: null,
      role: 'consultant',
      isOnline: false,
      lastSeenAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      bio: 'Business strategy consultant specializing in startup growth and market entry.',
      rating: 4.7,
      reviewCount: 89,
      specialization: 'Business Strategy',
    },
    lastMessage: 'I\'ll review your business plan and get back to you.',
    lastMessageAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
  },
  {
    id: 'conv-3',
    participant: {
      id: 'user-4',
      name: 'Lina Hassan',
      avatarUrl: null,
      role: 'specialist',
      isOnline: true,
      lastSeenAt: null,
      bio: 'Mental health counselor focusing on anxiety, stress management, and personal growth.',
      rating: 5.0,
      reviewCount: 211,
      specialization: 'Mental Health & Wellness',
    },
    lastMessage: 'Thank you for sharing that. Let\'s explore this further.',
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
  },
  {
    id: 'conv-4',
    participant: {
      id: 'user-5',
      name: 'Omar Faisal',
      avatarUrl: null,
      role: 'consultant',
      isOnline: false,
      lastSeenAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      bio: 'Financial planning expert with a focus on long-term wealth management.',
      rating: 4.6,
      reviewCount: 62,
      specialization: 'Financial Planning',
    },
    lastMessage: 'I\'ve sent you the investment portfolio review.',
    lastMessageAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
  },
  {
    id: 'conv-5',
    participant: {
      id: 'user-6',
      name: 'Rania Mostafa',
      avatarUrl: null,
      role: 'specialist',
      isOnline: false,
      lastSeenAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      bio: 'Nutritionist and wellness coach helping clients build sustainable healthy habits.',
      rating: 4.8,
      reviewCount: 97,
      specialization: 'Nutrition & Wellness',
    },
    lastMessage: 'Here is your personalized meal plan for next week.',
    lastMessageAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'user-2',
      senderName: 'Dr. Sara Al-Mansouri',
      messageText: 'Hello! I\'m looking forward to our consultation session.',
      payload: { type: 'text', content: 'Hello! I\'m looking forward to our consultation session.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
    },
    {
      id: 'msg-2',
      conversationId: 'conv-1',
      senderId: 'current-user',
      senderName: 'Consultant',
      messageText: 'Thank you, Dr. Sara! I have been looking forward to this as well. I have a few topics I\'d like to discuss.',
      payload: { type: 'text', content: 'Thank you, Dr. Sara! I have been looking forward to this as well. I have a few topics I\'d like to discuss.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
      isOwn: true,
    },
    {
      id: 'msg-3',
      conversationId: 'conv-1',
      senderId: 'user-2',
      senderName: 'Dr. Sara Al-Mansouri',
      messageText: 'Great! I\'ve confirmed the appointment. See you on Thursday.',
      payload: {
        type: 'appointment',
        appointment: {
          id: 'apt-1',
          title: 'Career Development Session',
          date: '2026-07-10',
          time: '15:00',
          duration: 60,
          sessionType: 'online',
          status: 'confirmed',
        },
      },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
    },
    {
      id: 'msg-4',
      conversationId: 'conv-1',
      senderId: 'current-user',
      senderName: 'Consultant',
      messageText: 'Great! I\'ve confirmed the appointment. See you on Thursday.',
      payload: { type: 'text', content: 'Great! I\'ve confirmed the appointment. See you on Thursday.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
      isOwn: true,
    },
    {
      id: 'msg-5',
      conversationId: 'conv-1',
      senderId: 'user-2',
      senderName: 'Dr. Sara Al-Mansouri',
      messageText: 'Here is the video invitation for our session.',
      payload: {
        type: 'video_invitation',
        session: {
          id: 'session-1',
          title: 'Career Development — Video Session',
          date: '2026-07-10',
          startTime: '15:00',
          joinUrl: 'https://bosla.app/video/session-1',
        },
      },
      status: 'delivered',
      createdAtUtc: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      isOwn: false,
    },
    {
      id: 'msg-6',
      conversationId: 'conv-1',
      senderId: 'user-2',
      senderName: 'Dr. Sara Al-Mansouri',
      messageText: 'Your next session is confirmed for Thursday at 3 PM.',
      payload: { type: 'text', content: 'Your next session is confirmed for Thursday at 3 PM.' },
      status: 'delivered',
      createdAtUtc: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
      isOwn: false,
    },
  ],
  'conv-2': [
    {
      id: 'msg-c2-1',
      conversationId: 'conv-2',
      senderId: 'current-user',
      senderName: 'Consultant',
      messageText: 'Hi Ahmed, I\'ve attached my business plan for review. Looking forward to your feedback.',
      payload: { type: 'text', content: 'Hi Ahmed, I\'ve attached my business plan for review. Looking forward to your feedback.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
    },
    {
      id: 'msg-c2-2',
      conversationId: 'conv-2',
      senderId: 'user-3',
      senderName: 'Ahmed Khalil',
      messageText: 'I\'ll review your business plan and get back to you.',
      payload: { type: 'text', content: 'I\'ll review your business plan and get back to you.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      isOwn: false,
    },
  ],
  'conv-3': [
    {
      id: 'msg-c3-1',
      conversationId: 'conv-3',
      senderId: 'current-user',
      senderName: 'Consultant',
      messageText: 'I\'ve been feeling overwhelmed lately and I\'m not sure how to manage the stress.',
      payload: { type: 'text', content: 'I\'ve been feeling overwhelmed lately and I\'m not sure how to manage the stress.' },
      status: 'read',
      createdAtUtc: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isOwn: true,
    },
    {
      id: 'msg-c3-2',
      conversationId: 'conv-3',
      senderId: 'user-4',
      senderName: 'Lina Hassan',
      messageText: 'Thank you for sharing that. Let\'s explore this further.',
      payload: { type: 'text', content: 'Thank you for sharing that. Let\'s explore this further.' },
      status: 'delivered',
      createdAtUtc: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isOwn: false,
    },
  ],
};
