import { generate } from 'rxjs';
import { environment } from '../../environments/environment';

const V = environment.apiBaseUrl;

export const API_ENDPOINTS = {
  auth: {
    register: `${V}/auth/register`,
    login: `${V}/auth/login`,
    googleLogin: `${V}/auth/google-login`,
    refresh: `${V}/auth/refresh`,
    logout: `${V}/auth/logout`,
    forgotPassword: `${V}/auth/forgot-password`,
    resetPassword: `${V}/auth/reset-password`,
    confirmEmail: `${V}/auth/confirm-email`,
    resendConfirmationEmail: `${V}/auth/resend-confirmation-email`,
  },
  users: {
    me: `${V}/users/me`,
    changePassword: `${V}/users/me/password`,
    setPassword: `${V}/users/me/set-password`,
    education: `${V}/users/me/education`,
    educationById: (id: string) => `${V}/users/me/education/${id}`,
    socialLinks: `${V}/users/me/social-links`,
    socialLinkById: (id: string) => `${V}/users/me/social-links/${id}`,
    byId: (id: string) => `${V}/users/${id}`,
  },
  notifications: {
    mine: `${V}/notifications`,
    unreadCount: `${V}/notifications/unread-count`,
    markAllRead: `${V}/notifications/read`,
    markRead: (id: string) => `${V}/notifications/${id}/read`,
  },
  appointments: {
    base: `${V}/Appointments`,
    byId: (id: string) => `${V}/Appointments/${id}`,
    myappointments: `${V}/Appointments/my-appointments`,
    bySpecialist: (specialistId: string) => `${V}/appointments/specialist/${specialistId}`,
    upcoming: `${V}/appointments/upcoming`,
    history: (id: string) => `${V}/appointments/${id}/history`,
    confirm: (id: string) => `${V}/appointments/${id}/confirm`,
    cancel: (id: string) => `${V}/appointments/${id}/cancel`,
    reschedule: (id: string) => `${V}/appointments/${id}/reschedule`,
    complete: (id: string) => `${V}/appointments/${id}/complete`,
    reject: (id: string) => `${V}/appointments/${id}/reject`,
    notes: (id: string) => `${V}/appointments/${id}/notes`,
    reviews: (id: string) => `${V}/appointments/${id}/reviews`,
    reminders: (id: string) => `${V}/appointments/${id}/reminders`,
    reminderById: (id: string, reminderId: string) =>
      `${V}/appointments/${id}/reminders/${reminderId}`,
  },
  conversations: {
    base: `${V}/conversations`,
    byId: (id: string) => `${V}/conversations/${id}`,
    participants: (id: string) => `${V}/conversations/${id}/participants`,
    participantById: (id: string, uid: string) => `${V}/conversations/${id}/participants/${uid}`,
    messages: (id: string) => `${V}/conversations/${id}/messages`,
    messageById: (id: string, mid: string) => `${V}/conversations/${id}/messages/${mid}`,
  },
  video: {
    generateToken: `${V}/video-sessions/generate-token`,
    sessionById: (id: string) => `${V}/video-sessions/${id}`,
    start: (id: string) => `${V}/video-sessions/${id}/start`,
    end: (id: string) => `${V}/video-sessions/${id}/end`,
    webhook: `${V}/webhooks/agora`,
  },
  specialists: {
    onboard: `${V}/specialists/onboard`,
    me: `${V}/specialists/me`,
    cancellationPolicy: `${V}/specialists/me/cancellation-policy`,
    bookingPolicy: `${V}/specialists/me/booking-policy`,
    availability: `${V}/specialists/me/availability`,
    availabilityById: (id: string) => `${V}/specialists/me/availability/${id}`,
    experience: `${V}/specialists/me/experience`,
    experienceById: (id: string) => `${V}/specialists/me/experience/${id}`,
    expertise: `${V}/specialists/me/expertise`,
    expertiseById: (id: string) => `${V}/specialists/me/expertise/${id}`,
    skills: `${V}/specialists/me/skills`,
    skillById: (id: string) => `${V}/specialists/me/skills/${id}`,
    tools: `${V}/specialists/me/tools`,
    toolById: (id: string) => `${V}/specialists/me/tools/${id}`,
    all: `${V}/specialists`,
    byId: (id: string) => `${V}/specialists/${id}`,
    availabilityFor: (id: string) => `${V}/specialists/${id}/availability`,
    reviewsFor: (id: string) => `${V}/specialists/${id}/reviews`,
    embeddingRefresh: `${V}/specialists/me/embedding/refresh`,
    dashboard: `${V}/specialists/me/dashboard`,
    myReviews: `${V}/specialists/me/reviews`,
   
  },
  lookup: {
    expertise: `${V}/lookup/expertise`,
    industries: `${V}/lookup/industries`,
    skills: `${V}/lookup/skills`,
    tools: `${V}/lookup/tools`,
  },
  payments: {
    base: `${V}/payments`,
    byId: (id: string) => `${V}/payments/${id}`,
    earnings: `${V}/specialists/me/earnings`,
  },
  ai: {
    search: `${V}/ai/search`,
    searchHistory: `${V}/ai/search/history`,
    searchFeedback: (id: string) => `${V}/ai/search/${id}/feedback`,
    summaryRegenerate: (id: string) => `${V}/ai/summaries/${id}/regenerate`,
  },
  admin: {
    specialists: `${V}/admin/specialists`,
    pendingSpecialists: `${V}/admin/specialists/pending`,
    specialistDetail: (id: string) => `${V}/admin/specialists/${id}`,
    verifySpecialist: (id: string) => `${V}/admin/specialists/${id}/verify`,
    specialistStatus: (id: string) => `${V}/admin/specialists/${id}/status`,
    createSpecialist: `${V}/admin/specialists`,
    updateSpecialist: (id: string) => `${V}/admin/specialists/${id}`,
    users: `${V}/admin/users`,
    userDetail: (id: string) => `${V}/admin/users/${id}`,
    userRoles: (id: string) => `${V}/admin/users/${id}/roles`,
    deactivateUser: (id: string) => `${V}/admin/users/${id}/deactivate`,
    reactivateUser: (id: string) => `${V}/admin/users/${id}/reactivate`,
    expertise: `${V}/admin/expertise`,
    expertiseById: (id: string) => `${V}/admin/expertise/${id}`,
    skills: `${V}/admin/skills`,
    skillById: (id: string) => `${V}/admin/skills/${id}`,
    tools: `${V}/admin/tools`,
    toolById: (id: string) => `${V}/admin/tools/${id}`,
    industries: `${V}/admin/industries`,
    industryById: (id: string) => `${V}/admin/industries/${id}`,
    appointments: `${V}/admin/appointments`,
    appointmentDetail: (id: string) => `${V}/admin/appointments/${id}`,
    confirmAppointment: (id: string) => `${V}/admin/appointments/${id}/confirm`,
    completeAppointment: (id: string) => `${V}/admin/appointments/${id}/complete`,
    cancelAppointment: (id: string) => `${V}/admin/appointments/${id}/cancel`,
    auditLogs: `${V}/admin/audit-logs`,
    auditLogById: (id: string) => `${V}/admin/audit-logs/${id}`,
    dashboard: `${V}/admin/dashboard`,
    embeddingsStatus: `${V}/admin/ai/embeddings`,
    embeddingsRebuild: `${V}/admin/ai/embeddings/rebuild`,
    payments: `${V}/admin/payments`,
    paymentDetail: (id: string) => `${V}/admin/payments/${id}`,
    refundPayment: (id: string) => `${V}/admin/payments/${id}/refund`,
  },
} as const;
